# Generated by Django 3.2 on 2024-03-06 07:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_userinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from='title'),
        ),
    ]
