# Generated by Django 3.2 on 2024-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_userinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(),
        ),
    ]
